### PR TITLE
Add files from Turing repo

### PR DESCRIPTION
**Pull request by devmotion**
This PR adds relevant files from the Turing repo in a `Turing/` subfolder, together with their history.

The files were extracted with [git-filter-repo](https://github.com/newren/git-filter-repo/):
```shell
git clone git@github.com:TuringLang/Turing.jl.git
cd Turing
git filter-repo --path src/contrib/inference/AdvancedSMCExtensions.jl --path src/core/container.jl --path src/inference/AdvancedSMC.jl --path test/core/container.jl --path test/inference/AdvancedSMC.jl --path-rename '':Turing/
git remote add origin git@github.com:TuringLang/AdvancedPS.jl.git
git pull --allow-unrelated-histories origin master
git checkout -b Turing
git push -u origin Turing
```

Hopefully this simplifies reviews of PRs such as https://github.com/TuringLang/AdvancedPS.jl/pull/11 (see, e.g., https://github.com/TuringLang/AdvancedPS.jl/pull/11#issuecomment-675566188) since it would be clearer what parts of the existing implementation in Turing were changed. Moreover, by keeping the history it might be easier to track down changes and understand the implementation better.

### CODE REVIEW

**Comment by yebai** [comment]
Thanks, @devmotion - this is very helpful!

**Comment by yebai** [comment]
@devmotion maybe we can rename these files in a new PR, so that changes in #11 can be recognised by Github?

**Comment by devmotion** [comment]
Sure, I just wanted to keep this PR clean.

**Comment by devmotion** [comment]
Maybe it would be good as well to generate the default package layout with an empty module in a separate PR first, e.g., with PkgTemplates?

**Comment by yebai** [comment]
> Maybe it would be good as well to generate the default package layout with an empty module in a separate PR first, e.g., with PkgTemplates?

Sounds good to me!

**Pull request merged**
